package com.bornomala.keyboard.suggestions.data.dictionary

import com.google.common.truth.Truth.assertThat
import org.junit.Test
import java.io.File

/**
 * The phonetic key is the contract between what the user types and the bundled index, so it is
 * tested from both ends: table-driven roman/Bangla pairs, and a re-derivation of every line of
 * the shipped `bn_phonetic.txt` (generated by `scripts/gen_bn_phonetic.py`, which mirrors
 * [BanglaPhoneticKey.banglaKey]) — the two implementations cannot drift without failing here.
 */
class BanglaPhoneticKeyTest {

    /** Roman spellings that must all reduce to the same key as the Bangla word they spell. */
    private val roundTrips = listOf(
        "শশা" to listOf("shosha"),
        "সা" to listOf("sa"),
        "ছাড়া" to listOf("chara", "chhara", "chaRa", "chhaRa"),
        "বোবা" to listOf("boba"),
        "কখনো" to listOf("kokhono"),
        "আমি" to listOf("ami"),
        "বাংলা" to listOf("bangla"),
        "সময়" to listOf("somoy"),
        "কৃষি" to listOf("krishi"),
        "অনেক" to listOf("onek"),
        "বল" to listOf("bol"),
        "চাঁদ" to listOf("cha^d"),
        "রং" to listOf("rong"),
        "বিশ্ব" to listOf("bishwo"),
        "ব্যাপার" to listOf("byapar"),
        "দেশ" to listOf("desh", "desh"),
        "লেখাপড়া" to listOf("lekhapoRa"),
    )

    @Test
    fun `roman spellings reduce to the key of the word they spell`() {
        for ((bangla, romans) in roundTrips) {
            val expected = BanglaPhoneticKey.banglaKey(bangla)
            assertThat(expected).isNotEmpty()
            for (roman in romans) {
                assertThat(BanglaPhoneticKey.romanKey(roman)).isEqualTo(expected)
            }
        }
    }

    /**
     * The reported regression: the inherent vowel between শ and শ was dropped *and* let the two
     * same-class consonants collapse, so `shosha` resolved to সা and space silently swapped it in.
     */
    @Test
    fun `inherent vowel keeps same-class consonants apart`() {
        assertThat(BanglaPhoneticKey.romanKey("shosha")).isEqualTo("ssa")
        assertThat(BanglaPhoneticKey.romanKey("sa")).isEqualTo("sa")
        assertThat(BanglaPhoneticKey.romanKey("shosha"))
            .isNotEqualTo(BanglaPhoneticKey.romanKey("sa"))
        assertThat(BanglaPhoneticKey.banglaKey("শশা")).isEqualTo("ssa")
        assertThat(BanglaPhoneticKey.banglaKey("সা")).isEqualTo("sa")
    }

    /** Genuinely adjacent same-class consonants (doubled letters, conjuncts) still collapse. */
    @Test
    fun `adjacent same-class consonants collapse`() {
        assertThat(BanglaPhoneticKey.romanKey("okkhor")).isEqualTo(BanglaPhoneticKey.romanKey("okhor"))
        assertThat(BanglaPhoneticKey.romanKey("bhalo")).isEqualTo(BanglaPhoneticKey.romanKey("valo"))
    }

    @Test
    fun `input without phonetic content has no key`() {
        assertThat(BanglaPhoneticKey.romanKey("")).isEmpty()
        assertThat(BanglaPhoneticKey.romanKey("123")).isEmpty()
        assertThat(BanglaPhoneticKey.banglaKey("")).isEmpty()
        assertThat(BanglaPhoneticKey.banglaKey("১২৩")).isEmpty()
    }

    /**
     * Every word in the shipped index must be reachable under its own key: the generator and
     * [BanglaPhoneticKey.banglaKey] agree, so roman input that keys to it finds it.
     */
    @Test
    fun `shipped index is consistent with banglaKey`() {
        val index = HashMap<String, List<String>>()
        File(INDEX_PATH).forEachLine { raw ->
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) return@forEachLine
            val tab = line.indexOf('\t')
            if (tab <= 0) return@forEachLine
            index[line.substring(0, tab)] = line.substring(tab + 1).split(' ')
        }
        assertThat(index).isNotEmpty()

        val unreachable = ArrayList<String>()
        for (words in index.values) {
            for (word in words) {
                val key = BanglaPhoneticKey.banglaKey(word)
                if (index[key]?.contains(word) != true) unreachable.add("$word -> $key")
            }
        }
        assertThat(unreachable).isEmpty()
    }

    /** The user-visible promise: typing the word's roman spelling surfaces it from the index. */
    @Test
    fun `chara resolves to chhaRa in the shipped index`() {
        val key = BanglaPhoneticKey.romanKey("chara")
        val line = File(INDEX_PATH).readLines().first { it.startsWith("$key\t") }
        assertThat(line.substringAfter('\t').split(' ')).contains("ছাড়া")
    }

    private companion object {
        const val INDEX_PATH = "src/main/assets/dictionaries/bn_phonetic.txt"
    }
}
